version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.17.6
      npm: 6.14.15
      python: 2.7

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - node ./index.js