 version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 14.17.6  
      npm: 6.14.15 
      python: 2.7 
    commands: 
      - npm install 
  build: 
    commands: 
      - npm run build 

 artifacts:  
     type: zip   files: ./build/*